public class AssignQ5B {
    public static void test(){
        //date firstDate=date.newInstance(2020,01,01);
        //date lastdate=date.newInstance(2020,01,31);
        //String firstDate = '2017-02-05T01:44:00.000Z';
        //DateTime resultDateTime = DateTime.ValueofGmt(inpputString.replace('T', ' ')); 
      //  list<Account>accList =[select Name from Account where CreatedDate>firstDate AND CreatedDate<lastDate And isDeleted=true ALL ROWS ];
       // undelete acclist;
    }

}